### ISSUE TITLE
Should handle "Cannot read property 'subscriptionId' of undefined" error

### ISSUE THREAD

**Issue by Tuesdaysgreen** [projectkudu/slingshot#17]
If you do a deployment and then refresh the page, an unhandled exception will be thrown that says "Cannot read property 'subscriptionId' of undefined".  The error is completely harmless, however we should probably handle it so it doesn't pollute our app insights metrics.

**Comment by davidebbo** [comment]
I believe I've seen this same pop up in demos, though the steps may have been different. I think for some user accounts, it always happened. Maybe some issue with their tenant or sub. Would be good to handle in cleaner way.
