### ISSUE TITLE
feedback/suggestions

### ISSUE THREAD

**Issue by bewest** [projectkudu/slingshot#20]
Howdy, thanks for making this feature.
I'm especially interested in using a button to quick start the auto-deploy feature, where it sets up continuous integration.

I think this is done via webhooks installed on a git repo supporting webhooks, which is owned by the user.  It would be very cool for a button to deploy and set the site up to auto-deploy from the repo owned by the user.

Additionally, potentially since you are obtaining permission from github, it would be awesome for my users if the button could also fork the repo, I can explain my rationale behind this in discussion if needed.

In any case, I've read through some of the code of this and kudu and realize this might be a fair undertaking.  In the meantime, I noticed some very nice error strings produced in slingshot.  However, when I tested the button on a non-existant repo, no warning messages were produced.  I think what happens in the code is the default/blank template gets used if a valid one can't be resolved.  From design POV, this seems like reasonable behavior.  It might be interesting to think about providing a lint service, and perhaps producing some warnings about "missing so using a blank template" to hopefully mitigate surprises and create a positive feedback loop.

**Comment by davidebbo** [comment]
Closing this one as we have #21 tracking the CI part. Feel free to open other issue to track individual specific things.
