### ISSUE TITLE
Doesn't deploy from a folder withing the repo

### ISSUE THREAD

**Issue by singhkay** [projectkudu/slingshot#24]
Deploy button doesn’t work from a folder within the repo. Can that be made to work? example below

https://github.com/azurermtemplates/azurermtemplates/tree/master/create-storage-account

**Comment by davidebbo** [comment]
So you're ok with the convention that the template name is always `azuredeploy.json`, but you just want it to work in a subfolder. Correct?

**Comment by singhkay** [comment]
yep, template azuredeploy.json name is fine.

**Comment by singhkay** [comment]
@davidebbo Any ETA on this? This is blocking for our community hackathon/contribution scenarios

**Comment by Tuesdaysgreen** [comment]
Hi there.  I just started working on it.  Should be done by tomorrow sometime.

**Comment by singhkay** [comment]
Awesome! Thanks @Tuesdaysgreen

**Comment by Tuesdaysgreen** [comment]
I deployed it, but I couldn't get your template to work because it said that my subscription wasn't registered.  I believe that's a back-end issue though.  Please try it out and let me know if you run into issues.

**Comment by singhkay** [comment]
Works! Thank you :)

**Comment by davidebbo** [comment]
It can pick up the path automatically. e.g. this sample: https://github.com/davidebbo-test/DeployButtonScheduler/tree/master/sub
