### ISSUE TITLE
Generic icon for other resources

### ISSUE THREAD

**Issue by singhkay** [projectkudu/slingshot#25]
Can we have a generic icon for other resources? One that doesn't represent deploying a website

**Comment by davidebbo** [comment]
Hey @bradygaster, how hard would it be for you to come up with a new flavor of your [icon](https://camo.githubusercontent.com/9285dd3998997a0835869065bb15e5d500475034/687474703a2f2f617a7572656465706c6f792e6e65742f6465706c6f79627574746f6e2e706e67) that has the Azure flag on it instead of the WebSites icon? Thanks!

**Comment by singhkay** [comment]
@davidebbo What about using the new Azure logo?

**Comment by davidebbo** [comment]
Oh, I didn't realized that was the new logo. Well, I'm fine with whichever is deemed more correct.

**Comment by singhkay** [comment]
I came up with these in the meantime 
![1](https://cloud.githubusercontent.com/assets/6164178/6479119/c215f16c-c1f4-11e4-94cd-034877caad64.png)

![2](https://cloud.githubusercontent.com/assets/6164178/6479117/bcb11198-c1f4-11e4-8f06-b6743d7d2e1c.png)

**Comment by davidebbo** [comment]
Ok, I changed http://azuredeploy.net/deploybutton.png to use that one. Github seems to do a bit of caching, so it may not show up right away on projects that already had it.

**Comment by singhkay** [comment]
@davidebbo Awesome, can you also add the other one as deploybutton_small.png as well?

**Comment by davidebbo** [comment]
It would be nice if we could get an svg instead so it would scale better. This is tracked by #28.

**Comment by davidebbo** [comment]
Ok, it's there: http://azuredeploy.net/deploybutton_small.png

**Comment by singhkay** [comment]
Thanks @davidebbo

**Comment by kanreisa** [comment]
@davidebbo @singhkay hey, It seems has margin than before.

![](https://yabumi.cc/14beb898e70a87b48b1098e2.png)

you can use this data if needed:

![deploybutton.png](https://yabumi.cc/14beb8bc1a52d0a540e3e4cd.png)
![deploybutton_small.png](https://yabumi.cc/14beb8c647cb55b3a5ee7173.png)

**Comment by davidebbo** [comment]
Thanks, I updated them.
