### ISSUE TITLE
SVG button image?

### ISSUE THREAD

**Issue by kanreisa** [projectkudu/slingshot#28]
I want a SVG button image for high-DPI display.

currently it you know blurry like this:
![](https://yabumi.cc/14bcc70d9ee4679b8f176297.png)

**Comment by davidebbo** [comment]
Yes, that doesn't look good. Technically, you can make the button point to any image URL without affecting the functionality. But we should try to do this. This also relate to #25, which discusses changing the icon.

**Comment by jfoshee** [comment]
FWIW, you can make a quick and dirty vector badge using [shields.io](http://shields.io) that matches the usual style: ![Deploy to Azure](https://img.shields.io/badge/Deploy-Azure-6EC0D9.svg)

    [![Deploy to Azure](https://img.shields.io/badge/Deploy-Azure-6EC0D9.svg)](https://azuredeploy.net/)

Would be nicer if it had the Azure logo in there, though. And I'm sure many will prefer the larger deploy button.

**Comment by jpoon** [comment]
+1

**Comment by rauchg** [comment]
@jfoshee smart solution btw – thank you

**Comment by rauchg** [comment]
(I'd like to get this button in SVG however)

**Comment by shrimpy** [comment]
here is the SVG file for the button.

http://azuredeploy.net/deploybutton.svg

![Deploy to Azure](http://azuredeploy.net/deploybutton.svg)

**Comment by kanreisa** [comment]
Thanks :birthday:

**Comment by shrimpy** [comment]
np! I will update our ReadMe later, so that eveyrone will notice it :tada:

**Comment by jpoon** [comment]
Awesome. Thanks!
