### ISSUE TITLE
way to distinguish optional parameters?

### ISSUE THREAD

**Issue by kanreisa** [projectkudu/slingshot#29]
Hi,

I'm using "Deploy to Azure button" to my **[this project](https://github.com/kanreisa/reichat)** (reichat).
and I added [`azuredeploy.json`](https://github.com/kanreisa/reichat/blob/master/azuredeploy.json) to get initial parameters.

**result**:

![](https://yabumi.cc/14bcc8f3e5dd5184695d35cb.png)

**problems**:

* users can't understand which are optional parameters.
* [ARM Template](https://msdn.microsoft.com/en-us/library/azure/dn835138.aspx) can't specify that parameter is optional?

**solutions**: (proposal)

* add the magic prefix or suffix word to parameter name (Is there already?)
* just empty defaultValue to optional? (**added** from comment)
 * maybe it's not necessarily optional. And vice versa.
* update schema...

**expected**:

![](https://yabumi.cc/14bcca1bb9cc1ab271b7d2e7.png)
(Heroku)

Thanks,

**Comment by davidebbo** [comment]
Not sure I completely follow. I see in your template that all parameters are optional. But from what I can see, the Deploy UI is correctly filling up all the boxes with the default values from your template, such that you can directly press Next. If a parameter was *not* optional, it wouldn't let you go to the next step.

Maybe I'm not understanding the problem?

**Comment by kanreisa** [comment]
@davidebbo 
It is a problem that it is difficult to understand visually.
see **expected**, that is displaying "**(optional)**"

**Comment by kanreisa** [comment]
FYI: https://github.com/kanreisa/reichat/blob/master/app.json#L21 (app.json / for Heroku)

**Comment by Tuesdaysgreen** [comment]
I just spoke to David about this and I think we agree that this is a good idea.  It looks like you've already discovered that "optional" parameters in ARM templates means an empty default value.  So if we see that situation, we could tell the user that they don't need to fill it in.

**Comment by Tuesdaysgreen** [comment]
Woops.  Accidentally closed the issue.

**Comment by kanreisa** [comment]
@Tuesdaysgreen thank you. I'm waiting for improvement!

**Comment by kanreisa** [comment]
:+1:
