### ISSUE TITLE
Do integer parameters work?

### ISSUE THREAD

**Issue by singhkay** [projectkudu/slingshot#37]
Looks like integer parameters are causing a problem using this template here https://github.com/azurermtemplates/azurermtemplates/tree/master/ubuntu-vm-zookeper-cluster. I've tested this to be working in PowerShell

![1](https://cloud.githubusercontent.com/assets/6164178/6770645/8d6933c8-d083-11e4-84e0-80fbbf64cf67.png)
![2](https://cloud.githubusercontent.com/assets/6164178/6770644/8d67f04e-d083-11e4-8d31-b5a66a7baeb3.png)

**Comment by davidebbo** [comment]
Seems this change was never pushed to production. Unfortunately, the repro repo https://github.com/azurermtemplates/azurermtemplates/tree/master/ubuntu-vm-zookeper-cluster is gone, so it's unclear how to validate the fix.

**Comment by Tuesdaysgreen** [comment]
Don't worry, my test template that I'm using has an integer example: https://github.com/Tuesdaysgreen/Test

**Comment by davidebbo** [comment]
Great! I verified that it does not work in production right now ([link](https://deploy.azure.com/?repository=https://github.com/Tuesdaysgreen/Test)), which is expected since that change set is not in.
