### ISSUE TITLE
SQL Server Locations are not loading.

### ISSUE THREAD

**Issue by SyntaxC4** [projectkudu/slingshot#41]
[Sample](https://deploy.azure.com/?repository=https://github.com/azure-webapp-samples/ToDoApp#/form/setup)

**Comment by davidebbo** [comment]
Here is the repo URL: https://github.com/azure-webapp-samples/ToDoApp

I'm surprised it's even treating it as a dropdown. I would have expected it to be a plain string, since we don't have any knowledge of the sqlDbCollation field. @Tuesdaysgreen?

**Comment by Tuesdaysgreen** [comment]
We do have special logic for sqlLocation.  I even confirmed from the network response that the locations are being returned, however the UI isn't populating it for some reason.  I need to debug.

**Comment by SyntaxC4** [comment]
Did I just name the property wrong? it looks like sqlServerLocation was the suggestion from the [blog post](https://elliotthamai.wordpress.com/2014/11/15/using-custom-arm-templates-with-the-deploy-to-azure-button/)

**Comment by davidebbo** [comment]
I think if you had named it incorrectly, it would have been treated as a plain text box. My guess is that it's a bug.

**Comment by davidebbo** [comment]
Fix is deployed. Can you please verify?

**Comment by davidebbo** [comment]
@Tuesdaysgreen shame on you, times two ;)

**Comment by SyntaxC4** [comment]
Confirmed that issue #41 is resolved!

**Comment by Tuesdaysgreen** [comment]
Sorry I got lazy.  Thanks for fixing.  :)
