### ISSUE TITLE
ForbiddenError while trying to use the deploy button

### ISSUE THREAD

**Issue by andrewmatveychuk** [projectkudu/slingshot#46]
In some cases you can receive the following error while trying to deploy an app to Azure:
![error](https://cloud.githubusercontent.com/assets/12231656/7488865/93effe2a-f3d8-11e4-8325-23e46e99b398.png).
I guess it might be related to some limitations of DreamSpark subscription because I have only it activated in my Azure account.
(This issue was transferred here from the original thread at https://github.com/madskristensen/MiniBlog/issues/191)

**Comment by davidebbo** [comment]
Couple things to try:

- does https://portal.azure.com/ work for you?
- how about https://resources.azure.com/?
- when you get the error above, can you use F12 tools to get the request details?

**Comment by andrewmatveychuk** [comment]
Both sites are accessible and work fine:
![resources azure](https://cloud.githubusercontent.com/assets/12231656/7515896/c0814542-f4d3-11e4-9c51-cdfa096d4a63.png)
![portal azure](https://cloud.githubusercontent.com/assets/12231656/7515897/c0819f92-f4d3-11e4-84f5-73b720fbde65.png)
I've captured the network traffic with IE F12 tools to a file http://1drv.ms/1DTZWC8
According to the log I get 500 HTTP error for https://deploy.azure.com/api/template?repositoryUrl=https:%2F%2Fgithub.com%2Fmadskristensen%2FMiniBlog

**Comment by davidebbo** [comment]
I'm guessing it's a Dreamspark specific issue. We'll need to investigate it.

**Comment by andrewmatveychuk** [comment]
Thank you for looking into this issue. Let me know if you need more details.

**Comment by davidebbo** [comment]
I reproed the issue with a Dreamspark subscription. Looks like the call we make to check if the site name is available is failing.

```
ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.

   at Microsoft.WindowsAzure.Management.WebSites.WebSiteOperations.<IsHostnameAvailableAsync>d__114.MoveNext()
```

More investigation needed.

**Comment by andrewmatveychuk** [comment]
@davidebbo were you able to check this solution with DreamSpark subscription? I am still receiving the same error with 500 error code and the following response:
> {"error":"ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.","exception":"Microsoft.WindowsAzure.CloudException: ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.\r\n   at Microsoft.WindowsAzure.Management.WebSites.WebSiteOperations.<IsHostnameAvailableAsync>d__114.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Slingshot.Controllers.ARMController.<GenerateResourceGroupName>d__5d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Slingshot.Controllers.ARMController.<GetTemplate>d__4a.MoveNext()"}

**Comment by davidebbo** [comment]
Sorry, not yet, I shouldn't have closed this. I did get a fix on the staging site, but it seems it runs into additional issue.

You can give it a try by going to https://deploy-staging.azure.com/?repository=https://github.com/Tuesdaysgreen/HelloWorlddemo. You shouldn't get the error above, but might run into a new one. Let me know.

**Comment by andrewmatveychuk** [comment]
You were right. I was able to proceed with the deployment form and schedule a deployment process but it ended with the following error:
![deployment error](https://cloud.githubusercontent.com/assets/12231656/7728998/1fd9ba46-ff1b-11e4-9d86-439e8707d74c.png)
> {"operations":{"value":[{"id":"/subscriptions/e1cef2f7-14c7-487d-be6f-71b29ac4b042/resourceGroups/HelloWorlddemo2c6f/deployments/HelloWorlddemo2c6f/operations/390D6FF15819DCF4","operationId":"390D6FF15819DCF4","properties":{"provisioningState":"Failed","timestamp":"2015-05-20T15:04:08.9775528Z","duration":"PT3.4492455S","trackingId":"63d11168-db52-41e7-b681-4dcc060f5efe","statusCode":"Forbidden","statusMessage":{"error":{"code":"BadRequest","message":""}},"targetResource":{"id":"/subscriptions/e1cef2f7-14c7-487d-be6f-71b29ac4b042/resourceGroups/HelloWorlddemo2c6f/providers/Microsoft.Web/serverfarms/HelloWorlddemo2c6f","resourceType":"Microsoft.Web/serverfarms","resourceName":"HelloWorlddemo2c6f"}}}]},"provisioningState":"Failed"}

**Comment by davidebbo** [comment]
Yes, that's what I get too. There must be some more differences with those accounts that I need to isolate.

**Comment by davidebbo** [comment]
Ok, this time it's fixed for real! I tried the button from miniblog (https://github.com/madskristensen/MiniBlog), and it all worked.

**Comment by andrewmatveychuk** [comment]
@davidebbo, I've tried to deploy the MiniBlog and successfully created a new web application under my DreamSpark subscription without any errors or warnings.
Thank you for you help, David!
