### ISSUE TITLE
Does not work when repository name contains "_" charactor

### ISSUE THREAD

**Issue by jsakamoto** [projectkudu/slingshot#47]
I try to using "Deploy to Azure" button, but my repository `https://github.com/jsakamoto/nagesen_web` has "_" charactor, then it cause "Invalid site name" error.

(Azure Web Apps accept only the name can contain letters, numbers, and hyphens (but the first and last character must be a letter or number))

![image](https://cloud.githubusercontent.com/assets/95908/7554528/f1576c10-f766-11e4-882d-076786093ed1.png)

One idea, it can avoid by replacing invalid charactor to hyphen "-".

Could you consider to treat this my problem?

thanks.

**Comment by davidebbo** [comment]
Yes, that looks like a bug. Changing it to hyphen would make sense.

**Comment by davidebbo** [comment]
Should work now. Let me know if you still see an issue.

**Comment by jsakamoto** [comment]
It is work fine well!  
![image](https://cloud.githubusercontent.com/assets/95908/7741345/b95327dc-ffb8-11e4-89d4-dd4ef1509116.png)

thank you :+1:
