### ISSUE TITLE
Handling for SQL Server collation

### ISSUE THREAD

**Issue by patrickebates** [projectkudu/slingshot#49]
Is there special handling for SQL Server collation and/or a special paramName which I may be overlooking?  Thanks.

**Comment by davidebbo** [comment]
Can you please provide more details about the scenario and the issue? Do you have a test repo with a template that demonstrates the issue?

**Comment by patrickebates** [comment]
More question than issue.  I'm trying to determine the paramName to use to enable a dropdown list for selecting SQL Server collation, if such handling is available.

**Comment by davidebbo** [comment]
There are no special param names. As long as you provide a list of allowedValues in the template, the UI will turn it into a dropdown list.

**Comment by patrickebates** [comment]
That's what I needed to confirm.  No support for having the list generated like siteLocation.  Thanks.

**Comment by davidebbo** [comment]
That's correct. Not sure if there is even an API that will return this list. For locations it's driven by an API, and not hard coded in the site.
