### ISSUE TITLE
'?' parameter can't add

### ISSUE THREAD

**Issue by nnasaki** [projectkudu/slingshot#50]
I am trying to add parameter for add WebApps AppSettings properties. I filling a ApiKey with `https://hoge.services.azureml.net/execute?api-version=2.0&details=true` and deployed.

![image](https://cloud.githubusercontent.com/assets/875216/8050608/dfc68656-0eaa-11e5-947b-6f231902b73d.png)

Here is my code:
https://github.com/nnasaki/AzureML_Recommend_Sample/tree/add-azure-deploy-button

```json
        {
          "apiVersion": "2014-11-01",
          "name": "appsettings",
          "type": "config",
          "dependsOn": [
            "[resourceId('Microsoft.Web/Sites', parameters('siteName'))]"
          ],
          "properties": {
            "WEBSITE_NODE_DEFAULT_VERSION": "0.10.32",
            "apiUrl": "[parameters('apiUrl')]",
            "apiKey": "[parameters('apiKey')]"
          }
        },
```

It doesn't show me any errors. But, I get only a "WEBSITE_NODE_DEFAULT_VERSION" property.

![image](https://cloud.githubusercontent.com/assets/875216/8050687/75e38a8e-0eac-11e5-9da4-6ec2826c48e2.png)

I have tried remove '?' character from a string with success.
Is it possible to filling a parameter with `https://hoge.services.azureml.net/execute?api-version=2.0&details=true` ?

**Comment by Tuesdaysgreen** [comment]
I'm able to reproduce your issue with your template if I add in the query parameter (?).  I think it has something to do with the API version because it seems to work correctly if I use an older API version (see https://github.com/Tuesdaysgreen/HelloWorldMVCAppSettingDemo).  If you need to get around this for now, you can try using the older 2014-04-01 API version.

**Comment by davidebbo** [comment]
Newest version `2015-06-01` fixes this without other syntax changes.

**Comment by nnasaki** [comment]
Thanks to @Tuesdaysgreen @davidebbo for my issue resolved!

I have tried newest version `2015-06-01` with no success. However,  I have tried changing `2014-04-01` so working.
