### ISSUE TITLE
Help Wanted - hostingPlanName not showing in portal

### ISSUE THREAD

**Issue by tomkerkhove** [projectkudu/slingshot#80]
I have a ARM template that deploys an API App with App Plan & Application Insights.

However, the `hostingPlanName` parameter is not showing, can somebody provide me with some help why it is hidden please?

You can find my repo [here](https://github.com/tomkerkhove/application-insights-arm).

**Comment by davidebbo** [comment]
I believe the way it works is that the hosting plan name is always implied from the site name. This was a scoping decision at the time to keep things simple in most common scenarios, but it does reduce flexibility in term of not being able to choose an existing Plan.

**Comment by tomkerkhove** [comment]
So basically this is done by convention and the Setup-page will not prompt you for this.
Fair enough, thank you for the info!

Closing this issue, thank you!
