### ISSUE TITLE
The website’s security certificate is not yet valid or has expired.  Error Code: DLG_FLAGS_SEC_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by ShyykoSerhiy** [projectkudu/slingshot#82]
It looks like the cert is messed up.
The website’s security certificate is not yet valid or has expired.  Error Code: DLG_FLAGS_SEC_CERT_DATE_INVALID

how to reproduce: 
open https://azuredeploy.net/

**Comment by davidebbo** [comment]
@ShyykoSerhiy Indeed, there was an issue! It is resolved now. Thanks for letting us know.
