### ISSUE TITLE
Deploy button doesn't work for any project

### ISSUE THREAD

**Issue by ShyykoSerhiy** [projectkudu/slingshot#86]
Steps to reproduce:
1. Open https://deploy.azure.com/?repository=https://github.com/rauchg/slackin#/form/setup
2. Observe "An error occurred while sending the request."

Exception from request to https://deploy.azure.com/api/template?repositoryUrl=https:%2F%2Fgithub.com%2Frauchg%2Fslackin

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
↵   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
↵   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
↵   --- End of inner exception stack trace ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at Slingshot.Concrete.GitHubRepository.<GetBranch>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
↵   at Slingshot.Controllers.ARMController.<GetTemplate>d__14.MoveNext()

**Comment by snobu** [comment]
Thank you for reporting this one. Related to recent GitHub crypto changes - https://githubengineering.com/crypto-removal-notice/. Fix on its way.

**Comment by davidebbo** [comment]
Thanks @snobu, that took care of it!
